name: Build and Compilation
on: [push]

jobs:
  build:
      name: Build and Compilation
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: make
          run: make
        - name: make bonus
          run: make bonus